<?php
// $Id: xoops_version.php,v 1.7 2003/02/12 11:39:13 okazu Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <https://www.xoops.org>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

$modversion['name'] = _MI_SYMANTECALERT_NAME;
$modversion['version'] = 1.00;
$modversion['description'] = _MI_SYMANTECALERT_DESC;
$modversion['author'] = 'Rudolph Jakob Heuser<br>( http://www.felocity.org )';
$modversion['credits'] = 'Symantec Anti-Virus Research Corp.';
$modversion['help'] = 'netproject.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/syamntec_slogo.gif';
$modversion['dirname'] = 'symantecalert';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
// $modversion['sqlfile']['mysql'] = "sql/mysql.sql";
// $modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
// $modversion['tables'][0] = "modprefx_tablename";

// Admin things
$modversion['hasAdmin'] = 0;
// $modversion['adminindex'] = "admin/index.php";
// $modversion['adminmenu'] = "admin/menu.php";

// Template Defintions
// 1 entry per template file
// $modversion['templates'][1]['file'] = 'modname_index.html';
// $modversion['templates'][1]['description'] = 'modname Index File';

// Blocks
$modversion['blocks'][1]['file'] = 'symalert.php';
$modversion['blocks'][1]['name'] = _MI_SYMANTECALERT_BNAME1;
$modversion['blocks'][1]['description'] = 'Symantec Alert Block';
$modversion['blocks'][1]['show_func'] = 'b_symantecalert_show_alertblock';
$modversion['blocks'][1]['edit_func'] = 'b_symantecalert_edit_alertblock';
$modversion['blocks'][1]['options'] = '5|5|5|1|1';
$modversion['blocks'][1]['template'] = 'symantecalert_block_alertblock.html';

// Menu
$modversion['hasMain'] = 0;

// Comments
$modversion['hasComments'] = 0;
// $modversion['comments']['itemName'] = 'unique id';
// $modversion['comments']['pageName'] = 'page to handle comments.php';

// Admin Configuration
// name:        name of config option for accessing its specified value.
//                 i.e. $xoopsModuleConfig['storyhome']
// title:       title of this config option displayed in config settings form
// description: description of this config option displayed under title
// formtype:    form element type used in config form for this option. can be one of either
//                 textbox, textarea, select, select_multi, yesno, group, group_multi
// valuetype:   value type of this config option. can be one of either
//                 int, text, float, array, or other
//                 form type of group_multi, select_multi must always be value type of array
// default:     the default value for this option
//                 ignore it if no default
//                 'yesno' formtype must be either 0(no) or 1(yes)
// options:     options to be displayed in selection box
//                 required and valid for 'select' or 'select_multi' formtype option only
//                 language constants can be used for array key, otherwise use integer

// Designer notes
// extracted from SARC site
// var symAmax = '3';
// var symSshow = '0';
// var symBORDcolor = 'aaaaaa';
// var symLmax = '1';
// var symRmax = '2';
// var symBACKcolor = 'black';
// var symFONTcolor = 'ffffff';
// var symLINKcolor = 'cccccc';
// var symTshow = '0';

// $modversion['config'][1]['name'] = 'symAmax';
// $modversion['config'][1]['title'] = '_MI_SYMANTECALERT_C_NAME1';
// $modversion['config'][1]['description'] = '_MI_SYMANTECALERT_C_DESC1';
// $modversion['config'][1]['formtype'] = 'text';
// $modversion['config'][1]['valuetype'] = 'int';
// $modversion['config'][1]['default'] = 5;
//$modversion['config'][1]['options'] = array('key' => value);

// $modversion['config'][2]['name'] = 'symLmax';
// $modversion['config'][2]['title'] = '_MI_SYMANTECALERT_C_NAME2';
// $modversion['config'][2]['description'] = '_MI_SYMANTECALERT_C_DESC2';
// $modversion['config'][2]['formtype'] = 'text';
// $modversion['config'][2]['valuetype'] = 'int';
// $modversion['config'][2]['default'] = 5;
//$modversion['config'][1]['options'] = array('key' => value);

// $modversion['config'][3]['name'] = 'symRmax';
// $modversion['config'][3]['title'] = '_MI_SYMANTECALERT_C_NAME3';
// $modversion['config'][3]['description'] = '_MI_SYMANTECALERT_C_DESC3';
// $modversion['config'][3]['formtype'] = 'text';
// $modversion['config'][3]['valuetype'] = 'int';
// $modversion['config'][3]['default'] = 5;
//$modversion['config'][1]['options'] = array('key' => value);

// $modversion['config'][4]['name'] = 'symTshow';
// $modversion['config'][4]['title'] = '_MI_SYMANTECALERT_C_NAME4';
// $modversion['config'][4]['description'] = '_MI_SYMANTECALERT_C_DESC4';
// $modversion['config'][4]['formtype'] = 'yesno';
// $modversion['config'][4]['valuetype'] = 'int';
// $modversion['config'][4]['default'] = 1;
// //$modversion['config'][1]['options'] = array('key' => value);

// $modversion['config'][5]['name'] = 'symSshow';
// $modversion['config'][5]['title'] = '_MI_SYMANTECALERT_C_NAME5';
// $modversion['config'][5]['description'] = '_MI_SYMANTECALERT_C_DESC5';
// $modversion['config'][5]['formtype'] = 'yesno';
// $modversion['config'][5]['valuetype'] = 'int';
// $modversion['config'][5]['default'] = 1;
//$modversion['config'][1]['options'] = array('key' => value);
